// Conjunto de avaliação: NENHUM texto aqui está na base inicial (seedData.ts).
// Mistura marcas que o modelo nunca viu com variações ruidosas de marcas conhecidas.
// Escrito pelo mesmo autor da base inicial, então tende a ser otimista em relação a
// extratos reais — por isso o app aprende com as correções do usuário.
import type { SeedLabel } from '../seedData';

export const HOLDOUT: ReadonlyArray<{ text: string; label: SeedLabel }> = [
  // alimentação
  { text: 'IFOOD *IFOOD', label: 'food' },
  { text: 'PAG*PADARIA DONA MARIA', label: 'food' },
  { text: 'IFD*HAMBURGUERIA ARTESANAL', label: 'food' },
  { text: 'SUPERMERCADO CONDOR 034', label: 'food' },
  { text: 'RESTAURANTE E PIZZARIA BELLA VISTA', label: 'food' },
  { text: 'MP*PADARIA E CONFEITARIA TRIGO', label: 'food' },
  { text: 'CASA DE CARNES BOI GORDO', label: 'food' },
  { text: 'ATACADO MIX SUPERMERCADOS', label: 'food' },
  { text: 'LANCHES E SUCOS DA PRACA', label: 'food' },
  { text: 'RAPPI*RESTAURANTE JAPONES', label: 'food' },
  { text: 'MERCADO CENTRAL FRUTAS', label: 'food' },
  // transporte
  { text: 'UBER *TRIP HELP.UBER.COM', label: 'transport' },
  { text: '99 TECNOLOGIA LTDA', label: 'transport' },
  { text: 'POSTO ALVORADA COMBUSTIVEIS', label: 'transport' },
  { text: 'AUTO POSTO RODOVIA 116', label: 'transport' },
  { text: 'ESTACIONAMENTO PREDIO COMERCIAL', label: 'transport' },
  { text: 'PEDAGIO ARTERIS', label: 'transport' },
  { text: 'RECARGA TRANSPORTE PUBLICO', label: 'transport' },
  { text: 'MECANICA AUTO CENTER SUL', label: 'transport' },
  { text: 'POSTO ICONIC ABASTECIMENTO', label: 'transport' },
  { text: 'UBER* PENDING', label: 'transport' },
  // lazer
  { text: 'CINEMARK SHOPPING IGUATEMI', label: 'entertainment' },
  { text: 'INGRESSOS SHOW ROCK IN RIO', label: 'entertainment' },
  { text: 'BAR E RESTAURANTE CHOPP', label: 'entertainment' },
  { text: 'STEAMGAMES.COM 4259522', label: 'entertainment' },
  { text: 'PARQUE AQUATICO DIVERSAO', label: 'entertainment' },
  { text: 'TEATRO GUAIRA INGRESSO', label: 'entertainment' },
  { text: 'LOCAL BALADA CLUB', label: 'entertainment' },
  { text: 'LOJA DE GAMES PLAYSTATION', label: 'entertainment' },
  // saúde
  { text: 'DROGARIA SAO JOAO 0231', label: 'health' },
  { text: 'FARMACIA PAGUE MENOS 889', label: 'health' },
  { text: 'CLINICA SAO FRANCISCO EXAMES', label: 'health' },
  { text: 'UNIMED SEGUROS SAUDE', label: 'health' },
  { text: 'ACADEMIA CROSSFIT BOX', label: 'health' },
  { text: 'CONSULTA ODONTOLOGICA', label: 'health' },
  { text: 'LABORATORIO CLINICO VIDA', label: 'health' },
  { text: 'DROGARIAS NISSEI', label: 'health' },
  { text: 'OTICAS CAROL', label: 'health' },
  // educação
  { text: 'ALURA ONLINE CURSOS TECNOLOGIA', label: 'education' },
  { text: 'UDEMY COURSE PURCHASE', label: 'education' },
  { text: 'MENSALIDADE FACULDADE ADS', label: 'education' },
  { text: 'ESCOLA DE IDIOMAS FISK', label: 'education' },
  { text: 'INSCRICAO PROCESSO SELETIVO', label: 'education' },
  { text: 'CURSO PREPARATORIO CONCURSO PUBLICO', label: 'education' },
  { text: 'COLEGIO E CURSO ANGLO', label: 'education' },
  { text: 'PAPELARIA E LIVRARIA ESCOLAR', label: 'education' },
  // compras
  { text: 'MERCADOLIVRE*3PRODUTOS', label: 'shopping' },
  { text: 'AMAZON.COM.BR', label: 'shopping' },
  { text: 'LOJAS RENNER SA 0456', label: 'shopping' },
  { text: 'SHEIN.COM', label: 'shopping' },
  { text: 'MAGAZINE LUIZA 0125', label: 'shopping' },
  { text: 'LOJA DE ROUPAS FEMININAS CHIC', label: 'shopping' },
  { text: 'SHOPEE BRASIL COMPRA', label: 'shopping' },
  { text: 'CALCADOS E BOLSAS OUTLET', label: 'shopping' },
  { text: 'KABUM COMERCIO ELETRONICO', label: 'shopping' },
  // casa
  { text: 'CONDOMINIO RESIDENCIAL JARDIM', label: 'home' },
  { text: 'RGE SUL DISTRIBUIDORA', label: 'home' },
  { text: 'ALUGUEL APARTAMENTO', label: 'home' },
  { text: 'CORSAN SANEAMENTO', label: 'home' },
  { text: 'CLARO NET FIBRA', label: 'home' },
  { text: 'MATERIAIS DE CONSTRUCAO SILVA', label: 'home' },
  { text: 'COMPANHIA DE ENERGIA ELETRICA', label: 'home' },
  { text: 'VIVO INTERNET RESIDENCIAL', label: 'home' },
  { text: 'LOJA DE MOVEIS E COLCHOES', label: 'home' },
  // viagem
  { text: 'AZUL LINHAS AEREAS BRASILEIRAS', label: 'travel' },
  { text: 'HOTEL BOUTIQUE CENTRO', label: 'travel' },
  { text: 'BOOKING.COM HOTEL', label: 'travel' },
  { text: 'LATAM AIR TRANSPORTE', label: 'travel' },
  { text: 'AIRBNB * HMXYZ12', label: 'travel' },
  { text: 'LOCADORA DE VEICULOS AEROPORTO', label: 'travel' },
  { text: 'DECOLAR.COM PASSAGENS', label: 'travel' },
  { text: 'POUSADA DO MAR', label: 'travel' },
  // assinaturas
  { text: 'NETFLIX.COM', label: 'subscription' },
  { text: 'DL*GOOGLE YOUTUBE MUSIC', label: 'subscription' },
  { text: 'SPOTIFY P1A2B3', label: 'subscription' },
  { text: 'DISNEY PLUS ASSINATURA', label: 'subscription' },
  { text: 'CLAUDE.AI SUBSCRIPTION', label: 'subscription' },
  { text: 'APPLE.COM/BILL ITUNES', label: 'subscription' },
  { text: 'AMAZON PRIME BR', label: 'subscription' },
  { text: 'GOOGLE *ICLOUD STORAGE', label: 'subscription' },
  { text: 'MICROSOFT*MICROSOFT 365 FAMILY', label: 'subscription' },
  // empréstimo
  { text: 'PARCELA CONSIGNADO INSS', label: 'loan' },
  { text: 'FINANCIAMENTO VEICULO PARCELA', label: 'loan' },
  { text: 'EMPRESTIMO PESSOAL PARCELA 3/12', label: 'loan' },
  // outros
  { text: 'TARIFA MANUTENCAO CONTA', label: 'other' },
  { text: 'ANUIDADE DIFERENCIADA CARTAO', label: 'other' },
  { text: 'PIX ENVIADO JOAO SILVA', label: 'other' },
  { text: 'SAQUE CAIXA ELETRONICO', label: 'other' },
  { text: 'PETZ PET SHOP', label: 'other' },
  { text: 'CORREIOS SEDEX', label: 'other' },
  { text: 'IOF INTERNACIONAL', label: 'other' },
];
