"""Base inicial de treino: estabelecimentos/descrições típicas de extrato brasileiro.

As chaves são os ids de categoria do FinanceFlow (src/lib/types.ts).
Essa base é escrita à mão e serve só para o modelo "sair do zero": as correções
do usuário (e o histórico dele) entram como exemplos extras e passam a pesar mais.
"""
from __future__ import annotations

import random

MERCHANTS: dict[str, list[str]] = {
    "food": [
        "IFOOD", "RAPPI", "MCDONALDS", "BURGER KING", "SUBWAY", "OUTBACK STEAKHOUSE", "SPOLETO",
        "GIRAFFAS", "HABIBS", "KFC", "DOMINOS PIZZA", "PIZZA HUT", "STARBUCKS", "PADARIA PAO QUENTE",
        "PADARIA SANTA CLARA", "SUPERMERCADO ZAFFARI", "CARREFOUR", "ATACADAO", "ASSAI ATACADISTA",
        "PAO DE ACUCAR", "MERCADO BIG", "SUPERMERCADOS GUANABARA", "RESTAURANTE SABOR CASEIRO",
        "LANCHONETE DO ZE", "ACOUGUE BOI GORDO", "HORTIFRUTI VERDE", "SORVETERIA ITALIANA",
        "CAFETERIA GRAO NOBRE", "CONFEITARIA DOCE VIDA", "ACAI DA ESQUINA", "SUSHI HOUSE", "CHURRASCARIA GAUCHA",
        "BAR E RESTAURANTE DO PORTO", "99FOOD", "ZE DELIVERY", "EMPORIO NATURAL", "PIZZARIA NAPOLI",
        "MERCADO MUNICIPAL", "SUPERMERCADO NACIONAL", "LANCHES E CIA", "DOCERIA BRIGADEIRO", "ESPETINHO DO GAUCHO",
        "COCO BAMBU", "MADERO", "BOBS", "PAPA JOHNS", "CASA DO PAO DE QUEIJO", "RESTAURANTE POR QUILO",
        "SACOLAO DO BAIRRO", "PADARIA E CONFEITARIA ESTRELA",
    ],
    "transport": [
        "UBER *TRIP", "UBER DO BRASIL", "UBER TRIP HELP.UBER.COM", "99 TAXI", "99APP", "99POP", "CABIFY",
        "POSTO IPIRANGA", "POSTO SHELL", "POSTO PETROBRAS", "AUTO POSTO SANTA FE", "SEM PARAR", "CONECTCAR",
        "PEDAGIO AUTOPISTA", "ESTACIONAMENTO CENTRO", "ESTAPAR", "METRO SP", "BILHETE UNICO", "SPTRANS",
        "RIOCARD", "VALE TRANSPORTE", "CPTM", "LOCALIZA RENT A CAR", "MOVIDA ALUGUEL", "OFICINA MECANICA SILVA",
        "BORRACHARIA DO JOAO", "LAVA RAPIDO", "DETRAN TAXA", "IPVA", "MULTA TRANSITO", "COMBUSTIVEL GASOLINA",
        "POSTO ALE", "POSTO BR MANIA", "AUTO PECAS CENTRAL", "TROCA DE OLEO", "ESTACIONAMENTO SHOPPING",
        "BILHETE ONIBUS", "PASSE ESTUDANTIL", "TAXI COOPERATIVA", "BLABLACAR", "YELLOW PATINETE", "CARTAO TRANSPORTE",
        "POSTO TEXACO", "AUTO CENTER", "CONCESSIONARIA REVISAO", "SEGURO AUTO PORTO", "ALCOOL ETANOL POSTO",
    ],
    "entertainment": [
        "CINEMARK", "KINOPLEX", "INGRESSO.COM", "SYMPLA", "EVENTIM", "STEAM GAMES", "PLAYSTATION STORE",
        "XBOX STORE", "NINTENDO ESHOP", "BAR DO ZE", "BALADA NOITE", "SHOW INGRESSO", "TEATRO MUNICIPAL",
        "PARQUE DE DIVERSOES", "BOLICHE", "CLUBE SOCIAL", "CERVEJARIA ARTESANAL", "PUB IRISH", "KARAOKE",
        "ESCAPE ROOM", "HOPI HARI", "BETO CARRERO", "CINEMA ARCOPLEX", "UCI CINEMAS", "CONCERTO MUSICAL",
        "BAR E BOTEQUIM", "CHOPERIA", "BILHETERIA FESTIVAL", "LOCADORA GAMES", "LAN HOUSE", "FUTEBOL ESTADIO",
        "TICKETMASTER", "TICKET360", "BLUEBOX BAR", "MUSEU INGRESSO", "ZOOLOGICO", "AQUARIO", "FLIPERAMA",
        "EPIC GAMES", "BATTLE NET BLIZZARD", "ROBLOX", "BAR DO PEIXE", "SINUCA BAR",
    ],
    "health": [
        "DROGASIL", "DROGARIA PACHECO", "RAIA DROGASIL", "PANVEL", "PAGUE MENOS", "FARMACIA POPULAR",
        "UNIMED", "AMIL SAUDE", "HAPVIDA", "DASA", "FLEURY", "LABORATORIO ANALISES", "CLINICA MEDICA",
        "DENTISTA ODONTO", "CLINICA ODONTOLOGICA", "PSICOLOGA CONSULTA", "FISIOTERAPIA", "SMART FIT",
        "BLUEFIT", "BODYTECH", "ACADEMIA", "CROSSFIT BOX", "HOSPITAL", "CONSULTA MEDICA", "OTICA DINIZ",
        "OFTALMOLOGISTA", "NUTRICIONISTA", "FARMACIA SAO JOAO", "DROGARIA CATARINENSE", "BRADESCO SAUDE",
        "SULAMERICA SAUDE", "NOTREDAME INTERMEDICA", "EXAME DE SANGUE", "PILATES STUDIO", "YOGA STUDIO",
        "VACINA CLINICA", "DERMATOLOGISTA", "GINECOLOGISTA", "SUPLEMENTOS WHEY", "GROWTH SUPLEMENTOS", "LABORATORIO SABIN",
        "TOTALPASS", "GYMPASS", "MEDICO PEDIATRA", "FARMACIA MANIPULACAO",
    ],
    "education": [
        "UNISENAC", "FIAP", "ALURA", "UDEMY", "COURSERA", "ESCOLA MUNICIPAL", "COLEGIO SANTA MARIA",
        "FACULDADE MENSALIDADE", "MENSALIDADE ESCOLAR", "CURSO DE INGLES", "WIZARD IDIOMAS", "CCAA IDIOMAS",
        "KUMON", "ESTRATEGIA CONCURSOS", "GRAN CURSOS ONLINE", "QCONCURSOS", "PLURALSIGHT", "ROCKETSEAT",
        "DIO DIGITAL INNOVATION", "ANHANGUERA", "UNOPAR", "INSCRICAO ENEM", "TAXA INSCRICAO CONCURSO",
        "MATERIAL ESCOLAR", "CURSO PREPARATORIO", "ESCOLA DE IDIOMAS", "CURSINHO PRE VESTIBULAR", "EDX ONLINE",
        "HOTMART CURSO", "EDUZZ CURSO", "SENAI CURSO", "SENAC CURSO", "UNIVERSIDADE FEDERAL TAXA", "ULBRA",
        "PUCRS MENSALIDADE", "CURSO DE PROGRAMACAO", "BOOTCAMP TECH", "ESCOLA DE MUSICA", "AULA PARTICULAR",
        "LIVROS DIDATICOS", "FUNDACAO CESGRANRIO", "BANCA CONCURSO TAXA", "ESCOLA DE DANCA",
    ],
    "shopping": [
        "MERCADO LIVRE", "MERCADOLIVRE", "AMAZON.COM.BR", "SHOPEE", "ALIEXPRESS", "SHEIN", "MAGAZINE LUIZA",
        "MAGALU", "AMERICANAS", "CASAS BAHIA", "LOJAS RENNER", "C&A MODAS", "RIACHUELO", "ZARA BRASIL",
        "HERING", "NIKE STORE", "ADIDAS", "CENTAURO", "NETSHOES", "KABUM", "SEPHORA", "O BOTICARIO",
        "NATURA COSMETICOS", "AREZZO", "SCHUTZ", "LIVRARIA CULTURA", "SARAIVA", "PAPELARIA KALUNGA", "LOJA DE ROUPAS",
        "CALCADOS CENTER", "AVON", "DAFITI", "SHOPPING CENTER", "FAST SHOP", "SAMSUNG STORE", "APPLE STORE",
        "LOJAS CEM", "PONTO FRIO", "MARISA", "FARM RIO", "OSKLEN", "RENNER", "MORANA", "HAVAN", "TIGELA ARTESANATO",
        "PERFUMARIA", "BIJUTERIA ACESSORIOS", "TEMU", "SHOPPING BARRA",
    ],
    "home": [
        "ALUGUEL", "CONDOMINIO", "TAXA CONDOMINIAL", "IPTU", "ENEL ENERGIA", "CPFL ENERGIA", "CEEE EQUATORIAL",
        "RGE SUL", "LIGHT ENERGIA", "CEMIG", "CORSAN", "SABESP", "SANEPAR", "COPASA", "VIVO FIBRA",
        "TIM LIVE", "OI FIBRA", "CLARO NET RESIDENCIAL", "BRISANET", "COMGAS", "ULTRAGAZ", "SUPERGASBRAS",
        "LEROY MERLIN", "TELHANORTE", "TOK&STOK", "ETNA MOVEIS", "MADEIREIRA", "ENCANADOR", "ELETRICISTA",
        "DIARISTA FAXINA", "SEGURO RESIDENCIAL", "MOVEIS PLANEJADOS", "COLCHOES", "INTERNET BANDA LARGA",
        "ENERGIA ELETRICA", "AGUA E ESGOTO", "GAS ENCANADO", "VIVO MOVEL PLANO", "TIM CELULAR", "CLARO MOVEL",
        "MATERIAL DE CONSTRUCAO", "LOJA DE UTILIDADES DOMESTICAS", "DECORACAO CASA", "CAMICADO", "TELEFONE FIXO",
        "FERRAGENS", "SERVICO DE DEDETIZACAO", "CHAVEIRO", "IMOBILIARIA",
    ],
    "travel": [
        "LATAM AIRLINES", "GOL LINHAS AEREAS", "AZUL LINHAS AEREAS", "DECOLAR", "BOOKING.COM", "AIRBNB",
        "HOTEL POUSADA", "POUSADA DO MAR", "CVC VIAGENS", "MAXMILHAS", "123 MILHAS", "HURB", "EXPEDIA",
        "RODOVIARIA PASSAGEM", "CLICKBUS", "BUSER VIAGEM", "PASSAGEM AEREA", "AEROPORTO", "TRIPADVISOR",
        "SEGURO VIAGEM", "AGENCIA DE VIAGENS", "RESORT ALL INCLUSIVE", "HOSTEL", "HOTEL IBIS", "HOTEL MERCURE",
        "HOTEL FASANO", "PASSAGEM ONIBUS INTERMUNICIPAL", "VIAGEM FERIAS", "TURISMO RECEITIVO", "PACOTE TURISTICO",
        "HOSPEDAGEM", "VRBO", "KAYAK", "SKYSCANNER", "TAP AIR PORTUGAL", "IBERIA", "LOCACAO CARRO VIAGEM",
        "PASSEIO TURISTICO", "TRANSFER AEROPORTO", "ESTADIA HOTEL", 
    ],
    "subscription": [
        "NETFLIX", "NETFLIX.COM", "SPOTIFY", "DISNEY PLUS", "HBO MAX", "MAX STREAMING", "AMAZON PRIME",
        "PRIME VIDEO", "YOUTUBE PREMIUM", "APPLE.COM/BILL", "ICLOUD", "GOOGLE ONE", "GLOBOPLAY", "DEEZER",
        "CRUNCHYROLL", "CANVA", "CHATGPT SUBSCRIPTION", "OPENAI", "ADOBE CREATIVE CLOUD", "MICROSOFT 365",
        "DROPBOX", "GITHUB", "NOTION", "PARAMOUNT PLUS", "TIDAL", "PLAYSTATION PLUS", "XBOX GAME PASS",
        "UBER ONE", "IFOOD CLUBE", "KINDLE UNLIMITED", "TINDER", "DUOLINGO", "APPLE MUSIC", "TELECINE", "STAR PLUS",
        "CLARO VIDEO", "LINKEDIN PREMIUM", "ZOOM", "FIGMA", "ANTHROPIC CLAUDE", "GOOGLE STORAGE", "NUVEMSHOP",
        "VERCEL", "CLUBE DE ASSINATURA", "REVISTA ASSINATURA", "JORNAL ASSINATURA DIGITAL", "SPOTIFY PREMIUM",
    ],
    "loan": [
        "PARCELA EMPRESTIMO", "EMPRESTIMO CONSIGNADO", "FINANCIAMENTO VEICULO", "FINANCIAMENTO IMOBILIARIO",
        "CAIXA HABITACAO", "SANTANDER FINANCIAMENTOS", "BV FINANCEIRA", "CREFISA", "BANCO PAN EMPRESTIMO",
        "JUROS CHEQUE ESPECIAL", "IOF", "CDC PARCELA", "CONSORCIO PARCELA", "PARCELAMENTO FATURA",
        "ENCARGOS ROTATIVO", "AYMORE FINANCIAMENTOS", "OMNI FINANCEIRA", "FACTA FINANCEIRA", "NUBANK EMPRESTIMO",
        "EMPRESTIMO PESSOAL", "PRESTACAO CASA PROPRIA", "FIES PARCELA", "JUROS E MULTA", "AMORTIZACAO",
        "SICREDI EMPRESTIMO", "BRADESCO FINANCIAMENTO", "ITAU CREDITO PESSOAL", "PAGAMENTO MINIMO FATURA JUROS",
        "REFINANCIAMENTO", "PARCELA CONSORCIO", "CARTAO CREDITO ENCARGOS", "MORA FATURA", "FINANCEIRA PARCELA",
    ],
    "other": [
        "PIX ENVIADO", "TRANSFERENCIA ENVIADA", "SAQUE CAIXA ELETRONICO", "SAQUE 24H", "DOACAO", "DIZIMO IGREJA",
        "TARIFA BANCARIA", "ANUIDADE CARTAO", "CORREIOS", "CARTORIO", "PET SHOP", "VETERINARIO", "LAVANDERIA",
        "BARBEARIA", "SALAO DE BELEZA", "PRESENTE ANIVERSARIO", "FLORICULTURA", "TAXA DIVERSAS", 
        "PAGAMENTO BOLETO", "TED ENVIADO", "DOC ENVIADO", "PIX PARA AMIGO", "PIX RACHA CONTA", "VAQUINHA ONLINE",
        "ASSOCIACAO MENSALIDADE", "SINDICATO CONTRIBUICAO", "GRAFICA XEROX", "COPIAS E IMPRESSOES", "CONSERTO CELULAR",
        "ASSISTENCIA TECNICA", "MANUTENCAO", "SERVICO AUTONOMO", "PAGAMENTO DIVERSOS", "TRANSFERENCIA ENTRE CONTAS",
    ],
}

PREFIXES = [
    "", "", "", "COMPRA CARTAO ", "COMPRA DEBITO ", "PAG*", "PAGTO ", "DEB AUTOM ",
    "COMPRA NO CREDITO ", "PAGAMENTO ", "TRANSF ",
]
SUFFIXES = [
    "", "", "", " SAO PAULO BR", " PELOTAS RS", " PORTO ALEGRE", " 01/03", " 02/10", " BRA", " *RS", " S.A.",
    " LTDA", " 1234", " CURITIBA", " 03/12", " MATRIZ",
]


def build_seed(variants: int = 3, seed: int = 42) -> list[tuple[str, str]]:
    """Gera (descrição, categoria) com variações típicas de extrato (prefixos, cidades, parcelas)."""
    rng = random.Random(seed)
    rows: list[tuple[str, str]] = []
    for category, merchants in MERCHANTS.items():
        for merchant in merchants:
            rows.append((merchant, category))
            for _ in range(variants - 1):
                text = f"{rng.choice(PREFIXES)}{merchant}{rng.choice(SUFFIXES)}".strip()
                rows.append((text, category))
    return rows
