// src/lib/ml/seedData.ts — base inicial de treino do classificador de gastos.
//
// Descrições escritas à mão no estilo de extratos/faturas brasileiros (caixa alta,
// prefixos de adquirente como "PAG*", "MP*", "IFD*", números de loja...).
// É uma base SINTÉTICA e pequena: serve para o modelo já funcionar no primeiro uso.
// A precisão real vem das correções do usuário, que viram novos exemplos de treino.

import type { ExpenseCategory } from '@/lib/types';

export type SeedLabel = ExpenseCategory;

const SEED: Record<string, string[]> = {
  food: [
    'IFOOD *RESTAURANTE SABOR CASEIRO', 'IFD*PIZZARIA NAPOLI', 'IFOOD *LANCHES DO ZE', 'RAPPI *BURGER HOUSE',
    'MC DONALDS', 'MCDONALDS 0456', 'BURGER KING 112', 'SUBWAY SHOPPING', 'SPOLETO MASSAS', 'GIRAFFAS',
    'OUTBACK STEAKHOUSE', 'PADARIA PAO QUENTE', 'PADARIA SAO JOSE LTDA', 'SUPERMERCADO BIG', 'CARREFOUR HIPERMERCADO',
    'ASSAI ATACADISTA', 'ATACADAO 087', 'MERCADO ZAFFARI', 'SUPERMERCADOS NACIONAL', 'PAO DE ACUCAR 0231',
    'EXTRA SUPERMERCADO', 'DIA SUPERMERCADOS', 'MERCEARIA DO ZE', 'HORTIFRUTI VERDEVIDA', 'ACOUGUE BOI NOBRE',
    'RESTAURANTE MINEIRO', 'LANCHONETE DO JOAO', 'STARBUCKS COFFEE', 'CAFE DO PONTO', 'SORVETERIA CREME MEL',
    'SUSHI HOUSE', 'DOMINOS PIZZA', 'HABIBS', 'BOBS 221', 'KFC BRASIL', 'CHINA IN BOX', 'MADERO BURGER',
    'DOCERIA VOVO ALICE', 'CONFEITARIA COLOMBO', 'PAG*RESTAURANTE SABOR', 'MP *LANCHES RAPIDOS', 'UBER EATS',
    'ZE DELIVERY BEBIDAS', 'ACAI CONCEITO', 'ESPETINHO DO GAUCHO', 'CHURRASCARIA FOGO DE CHAO', 'RESTAURANTE POR KILO',
    'BOTECO DO ZE', 'COFFEE LAB', 'PIZZARIA FORNO A LENHA', 'EMPORIO NATURAL ALIMENTOS', 'MERCADO MUFFATO',
  ],
  transport: [
    'UBER *TRIP', 'UBER *UBER', 'UBER DO BRASIL', '99 *99POP', '99APP', '99 TAXI', 'CABIFY BRASIL',
    'POSTO IPIRANGA', 'POSTO SHELL 0987', 'POSTO BR', 'AUTO POSTO SAO CRISTOVAO', 'POSTO PETROBRAS',
    'COMBUSTIVEIS E LUBRIFICANTES', 'SEM PARAR', 'CONECTCAR', 'VELOE TAG', 'ESTACIONAMENTO CENTRAL',
    'ESTAPAR', 'ZONA AZUL DIGITAL', 'PEDAGIO ECOVIAS', 'PEDAGIO AUTOPISTA', 'METRO SP BILHETE', 'BILHETE UNICO RECARGA',
    'SPTRANS', 'RIOCARD RECARGA', 'PASSAGEM ONIBUS URBANO', 'BORRACHARIA DO CARLAO', 'OFICINA MECANICA SILVA',
    'AUTO PECAS BRASIL', 'LAVA JATO EXPRESS', 'IPVA 2026', 'DETRAN LICENCIAMENTO', 'TRENSURB', 'VOLTZ MOTO',
    'POSTO ALE', 'TROCA DE OLEO LUBRIFICANTES', 'CENTRO AUTOMOTIVO', 'PNEUS E RODAS', 'SEGURO AUTO PORTO',
    'ESTACIONAMENTO SHOPPING', 'YELLOW PATINETE', 'BR MANIA COMBUSTIVEL',
  ],
  entertainment: [
    'CINEMARK', 'CINEPOLIS', 'INGRESSO.COM', 'SYMPLA INGRESSOS', 'EVENTIM', 'STEAM PURCHASE', 'PLAYSTATION STORE',
    'XBOX LIVE STORE', 'NINTENDO ESHOP', 'GOOGLE PLAY GAME', 'EPIC GAMES', 'BAR E CHOPERIA', 'BALADA NOTURNA',
    'CLUBE SOCIAL', 'BOLICHE', 'KARTODROMO', 'TEATRO MUNICIPAL', 'SHOW AO VIVO', 'PARQUE DE DIVERSOES',
    'ESCAPE ROOM', 'PUB IRLANDES', 'BAR DO ALEMAO', 'CASA DE SHOWS', 'FESTA ENTRETENIMENTO', 'BILHETERIA FESTIVAL',
    'LIVRARIA CULTURA LIVROS', 'ROLE BAR', 'SINUCA BAR', 'LOJA DE JOGOS GAMES', 'CINEMA KINOPLEX', 'HQ GIBIS',
  ],
  health: [
    'DROGASIL', 'DROGARIA SAO PAULO', 'DROGARIA PACHECO', 'PANVEL FARMACIAS', 'RAIA DROGASIL', 'FARMACIA POPULAR',
    'ULTRAFARMA', 'PAGUE MENOS', 'UNIMED', 'HAPVIDA', 'AMIL SAUDE', 'SULAMERICA SAUDE', 'BRADESCO SAUDE',
    'LABORATORIO DELBONI', 'DASA EXAMES', 'FLEURY', 'CLINICA ODONTOLOGICA', 'DENTISTA SORRISO', 'CONSULTORIO MEDICO',
    'HOSPITAL SAO LUCAS', 'PSICOLOGA CONSULTA', 'FISIOTERAPIA E PILATES', 'SMARTFIT', 'BLUEFIT ACADEMIA',
    'TOTALPASS', 'OTICA DINIZ', 'CLINICA OFTALMOLOGICA', 'NUTRICIONISTA', 'LABORATORIO DE ANALISES CLINICAS',
    'FARMACIA SAO JOAO', 'FARMACIA DO TRABALHADOR', 'ACADEMIA POWER GYM', 'DROGARIA CATARINENSE', 'CLINICA DERMATOLOGICA',
  ],
  education: [
    'FIAP', 'UNISENAC', 'ESTACIO DE SA', 'UNIP', 'ANHANGUERA', 'MENSALIDADE ESCOLAR', 'COLEGIO SANTA MARIA',
    'ESCOLA MUNICIPAL', 'UDEMY', 'COURSERA', 'ALURA CURSOS', 'ROCKETSEAT', 'CCAA IDIOMAS', 'WIZARD IDIOMAS',
    'FISK CURSO DE INGLES', 'CULTURA INGLESA', 'PAPELARIA KALUNGA', 'XEROX COPIAS', 'CURSINHO PREPARATORIO',
    'INSCRICAO CONCURSO', 'QCONCURSOS', 'ESTRATEGIA CONCURSOS', 'GRAN CURSOS ONLINE', 'FGV EDUCACAO', 'DIO DIGITAL INNOVATION',
    'FACULDADE MATRICULA', 'POS GRADUACAO MENSALIDADE', 'LIVRARIA UNIVERSITARIA', 'PROVA CERTIFICACAO', 'EXAME PROFICIENCIA',
    'PLATAFORMA DE CURSOS EAD', 'MATERIAL ESCOLAR',
  ],
  shopping: [
    'AMAZON MARKETPLACE', 'AMAZON BR', 'MERCADO LIVRE', 'MERCADOLIVRE*COMPRA', 'MAGAZINE LUIZA', 'MAGALU',
    'LOJAS AMERICANAS', 'CASAS BAHIA', 'SHOPEE', 'ALIEXPRESS', 'SHEIN', 'LOJAS RENNER', 'C&A MODAS', 'RIACHUELO',
    'ZARA BRASIL', 'HERING', 'NETSHOES', 'CENTAURO', 'DAFITI', 'KABUM', 'PONTO FRIO', 'FAST SHOP',
    'SEPHORA', 'O BOTICARIO', 'NATURA COSMETICOS', 'AREZZO', 'HAVAIANAS', 'LOJA DE ROUPAS MODA', 'CALCADOS E ACESSORIOS',
    'PERFUMARIA', 'ELETRONICOS E INFORMATICA', 'SHOPPING CENTER LOJA', 'MERCADOLIVRE PRODUTO', 'AMERICANAS.COM', 'TERABYTE SHOP',
    'LOJA DE PRESENTES', 'BAZAR DA ESQUINA', 'SALAO DE BELEZA', 'BARBEARIA VIKING',
  ],
  home: [
    'ALUGUEL', 'CONDOMINIO RESIDENCIAL', 'IMOBILIARIA ALUGUEL', 'ENEL DISTRIBUICAO', 'CEMIG', 'CPFL ENERGIA', 'RGE SUL',
    'CELESC', 'COPEL', 'LIGHT SERVICOS DE ELETRICIDADE', 'SABESP', 'CORSAN', 'COPASA', 'SANEPAR', 'COMGAS',
    'ULTRAGAS BOTIJAO', 'LEROY MERLIN', 'TELHA NORTE', 'TOK&STOK', 'CASA E CONSTRUCAO', 'MATERIAL DE CONSTRUCAO',
    'IPTU', 'VIVO FIBRA', 'CLARO NET RESIDENCIAL', 'OI FIBRA', 'TIM CONTROLE', 'CLARO MOVEL', 'VIVO MOVEL',
    'MOVEIS E DECORACAO', 'ETNA', 'CAMICADO UTILIDADES', 'ENCANADOR SERVICO', 'ELETRICISTA SERVICO', 'ADMINISTRADORA DE CONDOMINIOS',
    'SEGURO RESIDENCIAL', 'GAS NATURAL', 'INTERNET BANDA LARGA', 'FAXINA DIARISTA',
  ],
  travel: [
    'LATAM AIRLINES', 'GOL LINHAS AEREAS', 'AZUL LINHAS AEREAS', 'AIRBNB', 'BOOKING.COM', 'HOTEL IBIS',
    'HOTEIS.COM', 'DECOLAR', '123MILHAS', 'CVC VIAGENS', 'EXPEDIA', 'POUSADA VISTA MAR', 'RESORT ALL INCLUSIVE',
    'LOCALIZA ALUGUEL DE CARROS', 'MOVIDA LOCADORA', 'UNIDAS ALUGUEL', 'RODOVIARIA PASSAGEM', 'CLICKBUS', 'BUSER VIAGENS',
    'AEROPORTO DUTY FREE', 'SEGURO VIAGEM', 'HURB', 'AGENCIA DE TURISMO', 'PASSAGEM AEREA', 'HOSTEL DOS VIAJANTES',
    'EMPRESA DE ONIBUS INTERMUNICIPAL', 'TRAVEL TURISMO', 'HOTEL FAZENDA',
  ],
  subscription: [
    'NETFLIX', 'NETFLIX.COM', 'SPOTIFY', 'SPOTIFY AB', 'YOUTUBE PREMIUM', 'GOOGLE *YOUTUBE', 'DISNEY PLUS', 'DISNEYPLUS',
    'HBO MAX', 'MAX.COM', 'AMAZON PRIME', 'PRIME VIDEO', 'GLOBOPLAY', 'APPLE.COM/BILL', 'ICLOUD', 'GOOGLE ONE',
    'GOOGLE *STORAGE', 'MICROSOFT 365', 'MICROSOFT*OFFICE', 'ADOBE CREATIVE CLOUD', 'OPENAI *CHATGPT SUBSCR', 'ANTHROPIC CLAUDE.AI',
    'NOTION LABS', 'CANVA PRO', 'DROPBOX', 'DEEZER', 'PARAMOUNT+', 'CRUNCHYROLL', 'TELECINE', 'PLAYSTATION PLUS',
    'XBOX GAME PASS', 'GITHUB', '1PASSWORD', 'LINKEDIN PREMIUM', 'UBER ONE', 'IFOOD CLUBE', 'AMAZON KINDLE UNLIMITED', 'AUDIBLE',
    'DUOLINGO PLUS', 'TIDAL',
  ],
  loan: [
    'EMPRESTIMO CONSIGNADO', 'PARCELA FINANCIAMENTO VEICULO', 'CREDITO PESSOAL PARCELA', 'REFINANCIAMENTO',
    'PARCELA EMPRESTIMO', 'EMPRESTIMO PESSOAL', 'FINANCIAMENTO IMOBILIARIO', 'CDC PARCELA', 'PARCELAMENTO DE FATURA',
    'JUROS ROTATIVO CARTAO', 'LIQUIDACAO CONTRATO CREDITO', 'CONSORCIO PARCELA',
  ],
  other: [
    'PIX ENVIADO', 'TRANSFERENCIA TED', 'TARIFA PACOTE SERVICOS', 'ANUIDADE CARTAO', 'IOF', 'SAQUE 24 HORAS',
    'DOACAO ONG', 'CORREIOS', 'CARTORIO', 'PETZ', 'COBASI', 'LAVANDERIA', 'FLORICULTURA', 'PRESENTE ANIVERSARIO',
    'TARIFA BANCARIA', 'MANUTENCAO DE CONTA', 'TRANSFERENCIA ENTRE CONTAS', 'PAGAMENTO BOLETO', 'DEPOSITO',
    'IGREJA DIZIMO', 'VETERINARIO', 'PET SHOP BANHO E TOSA', 'CHAVEIRO', 'GRAFICA RAPIDA', 'ASSOCIACAO MENSALIDADE',
    'IOF COMPRA INTERNACIONAL', 'AJUSTE DE SALDO', 'TAXA ADMINISTRATIVA',
  ],
};

export const SEED_EXAMPLES: ReadonlyArray<{ text: string; label: SeedLabel }> = Object.entries(SEED).flatMap(
  ([label, texts]) => texts.map((text) => ({ text, label: label as SeedLabel })),
);
